name: Prune Caches
run-name: "${{ github.event.workflow_run.display_title }} [${{ github.event.workflow_run.event }} ${{ github.event.workflow_run.head_branch }}]"

on:
  workflow_run:
    workflows: [ "Check, Build and Test" ]
    types: [ completed ]

jobs:
  prune-caches:
    name: "Prune Caches"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: "Add link to trigger workflow to summary"
        run: >
          echo 'Trigger: [${{ github.event.workflow_run.display_title }}
          [${{ github.event.workflow_run.event }}
          ${{ github.event.workflow_run.head_branch }}]](
          ${{ github.event.workflow_run.html_url }})' >> $GITHUB_STEP_SUMMARY
      - run: .github/prune-all-caches.sh
